apiVersion: v1
kind: Pod

metadata:
  name: datascientest-pod

spec:
  containers:
    - name: nginx
      image: nginx
      imagePullPolicy: IfNotPresent

      volumeMounts:
        - name: datascientest-volume
          mountPath: /usr/share/nginx/html/

      ports:
        - containerPort: 80

  volumes:
    - name: datascientest-volume
      persistentVolumeClaim:
        claimName: pvc-datascientest
